// <auto-generated />
using System;
using EnrollmentService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnrollmentService.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250617135622_UpdateEnrollmentTable")]
    partial class UpdateEnrollmentTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("EnrollmentService.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataMatricula")
                        .HasColumnType("TEXT")
                        .HasColumnName("EnrollmentDate");

                    b.Property<int>("IdAluno")
                        .HasColumnType("INTEGER")
                        .HasColumnName("StudentId");

                    b.Property<int>("IdCurso")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CourseId");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("Notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Enrolled")
                        .HasColumnName("Status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("DataMatricula")
                        .HasDatabaseName("IX_Enrollment_Date");

                    b.HasIndex("IdAluno")
                        .HasDatabaseName("IX_Enrollment_Student");

                    b.HasIndex("IdCurso")
                        .HasDatabaseName("IX_Enrollment_Course");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Enrollment_IsActive");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Enrollment_Status");

                    b.HasIndex("IdAluno", "IdCurso")
                        .IsUnique()
                        .HasDatabaseName("IX_Enrollment_Student_Course");

                    b.HasIndex("IsActive", "Status")
                        .HasDatabaseName("IX_Enrollment_Active_Status");

                    b.ToTable("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
